# Generated by Django 3.0 on 2019-12-22 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('red', 'Красная'), ('blue', 'Синяя'), ('green', 'Арбузик')], default='red', max_length=5, unique=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('solo', 'Я выстапую один'), ('group', 'Мы - группа')], default='solo', max_length=5)),
                ('day', models.SmallIntegerField(choices=[(1, 'Первый день'), (2, 'Второй день')], default=1)),
                ('info', models.TextField()),
                ('status', models.CharField(choices=[('under_consideration', 'Заявка на рассмотрении'), ('accepted', 'Участие подтверждено'), ('denied', 'Заяка отклонена')], default='under_consideration', max_length=19)),
                ('voices_for', models.SmallIntegerField(default=0)),
                ('voices_against', models.SmallIntegerField(default=0)),
                ('voices_abstain', models.SmallIntegerField(default=0)),
                ('total_voices', models.SmallIntegerField()),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fest_app.Scene')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_vote', 'Может голосовать'), ('can_create', 'Может создавать заявку'), ('see_status', 'Просматривать статус')],
            },
        ),
    ]
