# Generated by Django 3.0 on 2019-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='first_day_evening_fact',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='first_day_evening_plan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='first_day_night_fact',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='first_day_night_plan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='first_day_noon_fact',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='first_day_noon_plan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='second_day_evening_fact',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='second_day_evening_plan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='second_day_night_fact',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='second_day_night_plan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='second_day_noon_fact',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='second_day_noon_plan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
