# Generated by Django 3.0 on 2019-12-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0003_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='newartist',
            name='time_slot',
            field=models.CharField(choices=[('day', 'День'), ('evening', 'Вечер'), ('night', 'Поздний вечер')], default='evening', max_length=7),
        ),
    ]
