# Generated by Django 3.0 on 2019-12-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0004_newartist_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='voice',
            field=models.CharField(max_length=14),
        ),
    ]
